-- Enable Row Level Security (Security best practice)
-- This ensures that even if API keys are exposed, rules control access.

-- 1. CINEMAS Table (Brand information)
CREATE TABLE cinemas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE, -- 'CGV', '메가박스', '롯데시네마'
    color_code TEXT, -- '#FF0000' for styling badges dynamically
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. EVENTS Table (The main goods info)
CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL, -- "듄: 파트 2"
    cinema_id BIGINT REFERENCES cinemas(id), -- Connects to Cinemas table
    goods_type TEXT, -- "TTT", "Original Ticket"
    period TEXT, -- "2024.02.28 ~ 소진 시"
    image_url TEXT,
    locations TEXT[], -- Array of strings for branches ["용산", "영등포"]
    official_url TEXT,
    status TEXT DEFAULT '진행중', -- '진행중', '마감임박', '종료'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. MOVIES Table (For future expansion: genres, cast, etc.)
CREATE TABLE movies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL UNIQUE,
    tmdb_id INTEGER, -- For linking with TMDB API later
    poster_path TEXT,
    release_date DATE
);

-- Policies (Row Level Security)
ALTER TABLE cinemas ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;

-- Allow ANYONE (Public) to READ data
CREATE POLICY "Public events are viewable by everyone" ON events
    FOR SELECT USING (true);

CREATE POLICY "Public cinemas are viewable by everyone" ON cinemas
    FOR SELECT USING (true);

-- Only SERVICE ROLE (Server/Admin) can INSERT/UPDATE (We will configure this later)
-- For now, we rely on the fact that Anon key only has SELECT if we don't add other policies.

-- SEED DATA (Initial Test Data)
INSERT INTO cinemas (name, color_code) VALUES 
('CGV', 'bg-red-600 text-white'), 
('메가박스', 'bg-purple-800 text-white'), 
('롯데시네마', 'bg-red-100 text-red-700 border border-red-200');

INSERT INTO events (title, cinema_id, goods_type, period, image_url, locations, official_url, status)
VALUES 
('듄: 파트 2', 1, 'TTT (That''s The Ticket)', '2024.02.28 ~ 소진 시', 'https://images.unsplash.com/photo-1534447677768-be436bb09401', ARRAY['용산아이파크몰', '왕십리'], 'https://cgv.co.kr', '진행중'),
('파묘', 2, '오리지널 티켓', '2024.02.22 ~ 소진 시', 'https://images.unsplash.com/photo-1440404653325-ab127d49abc1', ARRAY['코엑스', '성수'], 'https://megabox.co.kr', '진행중');
